### ISSUE TITLE
sample_bigtiff.tif appears to be an invalid image

### ISSUE THREAD

**Issue by tomhughes** [naturalatlas/node-gdal#139]
The `sample_bigtiff.tif` image used by some of the tests does appear to be an invalid image, and the only reason it can be opened with the bundled libgdal is that it configures it's bundled libtiff with `--enable-defer-strile-load` which defers accessing certain data.

Trying to open it with my distribution libtiff just results in an error:

```
% tiffinfo test/data/sample_bigtiff.tif
TIFFFetchStripThing: IO error during reading of "StripOffsets".
```

Even rebuilding with `--enable-defer-strile-load` still gives errors, though it does manage to read enough of the image to print some information:

```
% tiffinfo test/data/sample_bigtiff.tif
TIFF Directory at offset 0x10 (16)
  Image Width: 100000 Image Length: 100000
  Bits/Sample: 8
  Sample Format: unsigned integer
  Compression Scheme: None
  Photometric Interpretation: min-is-black
  Samples/Pixel: 1
  Rows/Strip: 1
  Planar Configuration: single image plane
TIFFFetchStripThing: IO error during reading of "StripOffsets".
TIFFFetchStripThing: IO error during reading of "StripByteCounts".
```

The effect of all this is a test failure when using the system libgdal on Fedora at least:

```
not ok 475 Open BIGTIFF should not throw
  Error: Error opening dataset
      at Object.type (/home/tom/rpm/BUILD/node-gdal-0.8.0/lib/gdal.js:568:17)
      at Context.<anonymous> (/home/tom/rpm/BUILD/node-gdal-0.8.0/test/open_bigtiff.test.js:15:15)
      at callFn (/usr/lib/node_modules/mocha/lib/runnable.js:223:21)
      at Test.Runnable.run (/usr/lib/node_modules/mocha/lib/runnable.js:216:7)
      at Runner.runTest (/usr/lib/node_modules/mocha/lib/runner.js:374:10)
      at /usr/lib/node_modules/mocha/lib/runner.js:452:12
      at next (/usr/lib/node_modules/mocha/lib/runner.js:299:14)
      at /usr/lib/node_modules/mocha/lib/runner.js:309:7
      at next (/usr/lib/node_modules/mocha/lib/runner.js:247:23)
      at Object._onImmediate (/usr/lib/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:354:15)
not ok 476 Open BIGTIFF should be able to read raster size
  TypeError: Cannot read property 'rasterSize' of undefined
      at Context.<anonymous> (/home/tom/rpm/BUILD/node-gdal-0.8.0/test/open_bigtiff.test.js:19:20)
      at callFn (/usr/lib/node_modules/mocha/lib/runnable.js:223:21)
      at Test.Runnable.run (/usr/lib/node_modules/mocha/lib/runnable.js:216:7)
      at Runner.runTest (/usr/lib/node_modules/mocha/lib/runner.js:374:10)
      at /usr/lib/node_modules/mocha/lib/runner.js:452:12
      at next (/usr/lib/node_modules/mocha/lib/runner.js:299:14)
      at /usr/lib/node_modules/mocha/lib/runner.js:309:7
      at next (/usr/lib/node_modules/mocha/lib/runner.js:247:23)
      at Object._onImmediate (/usr/lib/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by brianreavis** [comment]
@GretaCB, do you have any ideas?

**Comment by GretaCB** [comment]
@brianreavis @tomhughes ah yes, this bigtiff file is a bit sneaky. You'll notice it is only 252 bytes. This is because it's simply a BigTIFF header with very minimal metadata in order for node-gdal to successfully detect and `gdal.open` the file. It's only meant for testing purposes and is not an actual image. The reason we use a minified test fixture is so that we dont have to store an actual BigTIFF (> 5GB) as a fixture, which can be costly size-wise.

**Comment by tomhughes** [comment]
How about http://download.compton.nu/tmp/sample_bigtiff.tif then? That is a bigtiff that is only 1.5Kb but maintains the 100000 pixel width (but is only one pixel high). It was created frpm sample.tif by:

```
tifftopnm sample.tif | pamscale -width=100000 -height=1 | pnmtotiff> sample_wide.tif
tiffcp -c zip -8 sample_wide.tif sample_bigtiff.tif
```

**Comment by brianreavis** [comment]
Perfect!
