### ISSUE TITLE
Contours from SRTM30

### ISSUE THREAD

**Issue by bjnortier** [naturalatlas/node-gdal#153]
I'm trying to create contours from an SRTM30 .hgt file, but can't get it to work. 

From the documentation I have to pass the destination layer into gdal.contourGenerate(), so I think I'm supposed to create a new layer in the *existing* dataset and pass it as 'dst', but that throws an error:

```
> const gdal = require('gdal');
> const dataset = gdal.open('./resources/S34E023.hgt');
> console.log(dataset);
Dataset {
  geoTransform: 
   [ 22.999583333333334,
     0.0008333333333333334,
     0,
     -32.999583333333334,
     0,
     -0.0008333333333333334 ],
  srs: SpatialReference {},
  driver: Driver { description: 'SRTMHGT' },
  rasterSize: { x: 1201, y: 1201 },
  layers: DatasetLayers {},
  bands: DatasetBands {},
  description: './resources/S34E023.hgt' }
  
> dataset.layers.create('contours', dataset.srs, gdal.MultiPolygon);
Error: Error creating layer
    at Error (native)
    at DatasetLayers.create (/Users/bjnortier/development/mission/node_modules/gdal/lib/gdal.js:650:17)
    at repl:1:16
    at REPLServer.defaultEval (repl.js:252:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:417:12)
    at emitOne (events.js:95:20)
    at REPLServer.emit (events.js:182:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
```

**Comment by bjnortier** [comment]
Ah, nevermind. I had a look in the tests (api_algorithms.test.js) and can see how to create new layers in memory.
