### ISSUE TITLE
Build errors on node 7.1.0

### ISSUE THREAD

**Issue by Svad** [naturalatlas/node-gdal#186]
Hi,

I ran into problems when building on node 7.1.0. After `npm install gdal` it returns error like that:
```
<compiler output above>
 CXX(target) Release/obj.target/gdal/src/gdal_dataset.o
../src/gdal_dataset.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE node_gdal::Dataset::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/gdal_dataset.cpp:147:16: error: ‘class v8::Object’ has no member named ‘SetHiddenValue’
   info.This()->SetHiddenValue(Nan::New("bands_").ToLocalChecked(), bands);
                ^
../src/gdal_dataset.cpp:150:16: error: ‘class v8::Object’ has no member named ‘SetHiddenValue’
   info.This()->SetHiddenValue(Nan::New("layers_").ToLocalChecked(), layers);
                ^
../src/gdal_dataset.cpp: In static member function ‘static Nan::NAN_GETTER_RETURN_TYPE node_gdal::Dataset::bandsGetter(v8::Local<v8::String>, Nan::NAN_GETTER_ARGS_TYPE)’:
../src/gdal_dataset.cpp:977:41: error: ‘class v8::Object’ has no member named ‘GetHiddenValue’
  info.GetReturnValue().Set(info.This()->GetHiddenValue(Nan::New("bands_").ToLocalChecked()));
                                         ^
../src/gdal_dataset.cpp: In static member function ‘static Nan::NAN_GETTER_RETURN_TYPE node_gdal::Dataset::layersGetter(v8::Local<v8::String>, Nan::NAN_GETTER_ARGS_TYPE)’:
../src/gdal_dataset.cpp:988:41: error: ‘class v8::Object’ has no member named ‘GetHiddenValue’
  info.GetReturnValue().Set(info.This()->GetHiddenValue(Nan::New("layers_").ToLocalChecked()));
                                         ^
gdal.target.mk:148: recipe for target 'Release/obj.target/gdal/src/gdal_dataset.o' failed
make: *** [Release/obj.target/gdal/src/gdal_dataset.o] Error 1
make: Leaving directory '/home/svad/prjs/geo-analytic-service/node_modules/gdal/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-47-generic
gyp ERR! command "/usr/local/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/svad/prjs/geo-analytic-service/node_modules/gdal/lib/binding/node-v51-linux-x64/gdal.node" "--module_name=gdal" "--module_path=/home/svad/prjs/geo-analytic-service/node_modules/gdal/lib/binding/node-v51-linux-x64"
gyp ERR! cwd /home/svad/prjs/geo-analytic-service/node_modules/gdal
gyp ERR! node -v v7.1.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/svad/prjs/geo-analytic-service/node_modules/gdal/lib/binding/node-v51-linux-x64/gdal.node --module_name=gdal --module_path=/home/svad/prjs/geo-analytic-service/node_modules/gdal/lib/binding/node-v51-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/svad/prjs/geo-analytic-service/node_modules/gdal/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:885:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.4.0-47-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/svad/prjs/geo-analytic-service/node_modules/gdal/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/svad/prjs/geo-analytic-service/node_modules/gdal
node-pre-gyp ERR! node -v v7.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok 
```
Looks like it is related to https://github.com/nodejs/nan/issues/587. So i resolved for myself this problem with pasting code from https://github.com/nodejs/nan/pull/599 and replacing every call of `SetHiddenValue`/`GetHiddenValue` with `SetPrivate`/`GetPrivate`.

E.g. `info.This()->SetHiddenValue(Nan::New("overviews_").ToLocalChecked(), overviews);` turned to `Nan::SetPrivate(info.This(),Nan::New("overviews_").ToLocalChecked(), overviews);`

`make test` gives promising result 
```
  537 passing (8s)
  8 pending
```
But i'm not sure this is the proper way to fix it.

**Comment by brianreavis** [comment]
We now support Node v7: https://github.com/naturalatlas/node-gdal/releases/tag/v0.9.4
