### ISSUE TITLE
Error opening dataset when opening grib file

### ISSUE THREAD

**Issue by boozedog** [naturalatlas/node-gdal#189]
I'm trying to open a grib file using the example script here: https://github.com/naturalatlas/node-gdal/blob/master/examples/gdalinfo.js

I'm getting the following error:

```
Error: Error opening dataset
    at Error (native)
    at Object.open (/Users/david/projects/grib/node_modules/gdal/lib/gdal.js:571:15)
    at Object.<anonymous> (/Users/david/projects/grib/gdalinfo.js:10:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
```

The grib file I'm trying to open is attached: [gfs.t12z.pgrb2.0p25.f000.zip](https://github.com/naturalatlas/node-gdal/files/769042/gfs.t12z.pgrb2.0p25.f000.zip)

**Comment by eschwartz** [comment]
It kind of looks like node-gdal is missing the [`GRIB` driver](http://www.gdal.org/frmt_grib.html)

Is there any way we can fix this? We use grib files extensively, and I'm really interested in being able to use node-gdal

**Comment by eschwartz** [comment]
I added a separate "feature request" ticket (#191) to support the GRIB driver
