### ISSUE TITLE
support node 9.8?

### ISSUE THREAD

**Issue by contra** [naturalatlas/node-gdal#229]
I'm sure you get this ticket every other week when a new release comes out.

```
error An unexpected error occurred: "/Users/contra/Projects/staeco/services/importer/node_modules/gdal: Command failed.
Exit code: 1
Command: sh
Arguments: -c node-pre-gyp install --fallback-to-build
Directory: /Users/contra/Projects/staeco/services/importer/node_modules/gdal
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@9.8.0 | darwin | x64
node-pre-gyp info check checked for \"/Users/contra/Projects/staeco/services/importer/node_modules/gdal/lib/binding/node-v59-darwin-x64/gdal.node\" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/gdal/v0.9.6/node-v59-darwin-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/gdal/v0.9.6/node-v59-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/gdal/v0.9.6/node-v59-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for gdal@0.9.6 and node@9.8.0 (node-v59 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/gdal/v0.9.6/node-v59-darwin-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@9.8.0 | darwin | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@9.8.0 | darwin | x64
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/contra/Projects/staeco/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/contra/Projects/staeco/services/importer/node_modules/gdal/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/contra/Projects/staeco/services/importer/node_modules/gdal/common.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/contra/Projects/staeco/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/contra/.node-gyp/9.8.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/contra/.node-gyp/9.8.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/contra/Projects/staeco/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/contra/.node-gyp/9.8.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/contra/Projects/staeco/services/importer/node_modules/gdal',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
  File \"../glob-files.py\", line 19
    print 'no argument'
                      ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(t 'no argument')?
gyp: Call to 'python ../glob-files.py \"proj/src/PJ_*.c\"' returned exit status 1 while in deps/libproj/libproj.gyp. while loading dependencies of deps/libgdal/libgdal.gyp while loading dependencies of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/contra/Projects/staeco/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 17.4.0
gyp ERR! command \"/Users/contra/.nvm/versions/node/v9.8.0/bin/node\" \"/Users/contra/Projects/staeco/node_modules/node-gyp/bin/node-gyp.js\" \"configure\" \"--fallback-to-build\" \"--module=/Users/contra/Projects/staeco/services/importer/node_modules/gdal/lib/binding/node-v59-darwin-x64/gdal.node\" \"--module_name=gdal\" \"--module_path=/Users/contra/Projects/staeco/services/importer/node_modules/gdal/lib/binding/node-v59-darwin-x64\" \"--python=/usr/bin/python\"
gyp ERR! cwd /Users/contra/Projects/staeco/services/importer/node_modules/gdal
gyp ERR! node -v v9.8.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/contra/.nvm/versions/node/v9.8.0/bin/node /Users/contra/Projects/staeco/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/contra/Projects/staeco/services/importer/node_modules/gdal/lib/binding/node-v59-darwin-x64/gdal.node --module_name=gdal --module_path=/Users/contra/Projects/staeco/services/importer/node_modules/gdal/lib/binding/node-v59-darwin-x64 --python=/usr/bin/python' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/contra/Projects/staeco/services/importer/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:936:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Darwin 17.4.0
node-pre-gyp ERR! command \"/Users/contra/.nvm/versions/node/v9.8.0/bin/node\" \"/Users/contra/Projects/staeco/services/importer/node_modules/gdal/node_modules/.bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
node-pre-gyp ERR! cwd /Users/contra/Projects/staeco/services/importer/node_modules/gdal
node-pre-gyp ERR! node -v v9.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/Users/contra/.nvm/versions/node/v9.8.0/bin/node /Users/contra/Projects/staeco/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/contra/Projects/staeco/services/importer/node_modules/gdal/lib/binding/node-v59-darwin-x64/gdal.node --module_name=gdal --module_path=/Users/contra/Projects/staeco/services/importer/node_modules/gdal/lib/binding/node-v59-darwin-x64 --python=/usr/bin/python' (1)".
```

**Comment by contra** [comment]
Closing as this is done now
