### ISSUE TITLE
failed npm install gdal

### ISSUE THREAD

**Issue by zj91zj** [naturalatlas/node-gdal#300]
$ npm install gdal

npm ERR! code 1
npm ERR! path /home/proton/vesta-server/nodeServer/node_modules/gdal
npm ERR! command failed
npm ERR! command sh -c -- node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute '/home/proton/.nvm/versions/node/v16.20.2/bin/node /home/proton/.nvm/versions/node/v16.20.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/proton/vesta-server/nodeServer/node_modules/gdal/lib/binding/gdal.node --module_name=gdal --module_path=/home/proton/vesta-server/nodeServer/node_modules/gdal/lib/binding --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.11
npm ERR! node-pre-gyp info using node@16.20.2 | linux | x64
npm ERR! node-pre-gyp info check checked for "/home/proton/vesta-server/nodeServer/node_modules/gdal/lib/binding/gdal.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/naturalatlas/node-gdal/releases/download/0.11.1/node-v93-linux-x64-glibc.tar.gz
npm ERR! node-pre-gyp ERR! install request to https://github.com/naturalatlas/node-gdal/releases/download/0.11.1/node-v93-linux-x64-glibc.tar.gz failed, reason: connect ETIMEDOUT 20.205.243.166:443
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for gdal@0.11.1 and node@16.20.2 (node-v93 ABI, glibc) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error request to https://github.com/naturalatlas/node-gdal/releases/download/0.11.1/node-v93-linux-x64-glibc.tar.gz failed, reason: connect ETIMEDOUT 20.205.243.166:443
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@16.20.2 | linux | x64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@16.20.2 | linux | x64
npm ERR! gyp info find Python using Python version 3.10.12 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/proton/.nvm/versions/node/v16.20.2/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/proton/vesta-server/nodeServer/node_modules/gdal/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/proton/vesta-server/nodeServer/node_modules/gdal/common.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/proton/.nvm/versions/node/v16.20.2/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/proton/.cache/node-gyp/16.20.2/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/proton/.cache/node-gyp/16.20.2',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/proton/.nvm/versions/node/v16.20.2/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/proton/.cache/node-gyp/16.20.2/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/proton/vesta-server/nodeServer/node_modules/gdal',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! /bin/sh: 1: python: not found
npm ERR! gyp: Call to 'python -c "import os;import platform;u=platform.uname();print((u[0] == 'Darwin' and int(u[2][0:2]) >= 13) and '-stdlib=libstdc++' not in os.environ.get('CXXFLAGS','') and '-mmacosx-version-min' not in os.environ.get('CXXFLAGS',''))"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/home/proton/.nvm/versions/node/v16.20.2/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:284:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Linux 6.5.0-15-generic
npm ERR! gyp ERR! command "/home/proton/.nvm/versions/node/v16.20.2/bin/node" "/home/proton/.nvm/versions/node/v16.20.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/proton/vesta-server/nodeServer/node_modules/gdal/lib/binding/gdal.node" "--module_name=gdal" "--module_path=/home/proton/vesta-server/nodeServer/node_modules/gdal/lib/binding" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
npm ERR! gyp ERR! cwd /home/proton/vesta-server/nodeServer/node_modules/gdal
npm ERR! gyp ERR! node -v v16.20.2
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/home/proton/.nvm/versions/node/v16.20.2/bin/node /home/proton/.nvm/versions/node/v16.20.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/proton/vesta-server/nodeServer/node_modules/gdal/lib/binding/gdal.node --module_name=gdal --module_path=/home/proton/vesta-server/nodeServer/node_modules/gdal/lib/binding --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/proton/vesta-server/nodeServer/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1100:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
npm ERR! node-pre-gyp ERR! System Linux 6.5.0-15-generic
npm ERR! node-pre-gyp ERR! command "/home/proton/.nvm/versions/node/v16.20.2/bin/node" "/home/proton/vesta-server/nodeServer/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /home/proton/vesta-server/nodeServer/node_modules/gdal
npm ERR! node-pre-gyp ERR! node -v v16.20.2
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.11
npm ERR! node-pre-gyp ERR! not ok

**Comment by zj91zj** [comment]
download https://github.com/naturalatlas/node-gdal/releases/download/0.11.1/node-v93-linux-x64-glibc.tar.gz, then unzip it, put binding/gdal.node into /node_modules/gdal/lib/binding
