### ISSUE TITLE
Module did not self register

### ISSUE THREAD

**Issue by ryanramage** [naturalatlas/node-gdal#87]
Using iojs I am getting this error

```
®[shp2json]$ shp2json 
module.js:341
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:341:32)
    at Function.Module._load (module.js:296:12)
    at Module.require (module.js:351:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/shp2json/node_modules/gdal/lib/gdal.js:7:29)
    at Module._compile (module.js:446:26)
    at Object.Module._extensions..js (module.js:464:10)
    at Module.load (module.js:341:32)
    at Function.Module._load (module.js:296:12)
```

I am making sure to be using gdal at 0.4.1. 

```
®[shp2json]$ node -v
v1.1.0
```

**Comment by springmeyer** [comment]
We provide binaries for node.js v0.10.x but not yet io.js. So this error is expected if you 1) installled originally with node.js and then 2) switched to io.js and tried to run things. To work with io.js several things will need to happen:

 - [ ] upgrade NAN and node-pre-gyp deps
 - [ ] ensure things compile with latest io.js
 - [ ] release new tag and binaries.

So, please stick to node.js 0.10.x for now if you'd like to use node-gdal.

**Comment by springmeyer** [comment]
0.12.x support will land as part of https://github.com/naturalatlas/node-gdal/issues/90

**Comment by lforrrrawx** [comment]
设置win-delay-load-hook为true即可
