### ISSUE TITLE
gdal.open() throws an error when trying to create a raster

### ISSUE THREAD

**Issue by asonnenschein** [naturalatlas/node-gdal#92]
The following function:
```
  function reproject(filePath) {

    var src
      , w
      , h
      , sSrs
      , tSrs
      , parsed
      , out
      , driver
      , geoTransform
      , res
      , tw
      , th
    ;

    src = gdal.open(filePath);
    w = src.rasterSize.x;
    h = src.rasterSize.y;

    gt = src.geoTransform;

    res = {
      x: gt[1],
      y: gt[5]
    };

    tw = Math.ceil(res.x);
    th = Math.ceil(res.y);

    sSrs = src.srs;
    tSrs = gdal.SpatialReference.fromUserInput('EPSG:4326');

    parsed = path.parse(filePath);
    out = path.join(program.outpath, parsed.name + parsed.ext);
    
    // here is where the code is failing
    dst = gdal.open(out, 'w', 'GTiff', tw, th);

    gdal.reprojectImage({
      src: src,
      dst: out,
      s_srs: sSrs,
      t_srs: tSrs
    });

  };
```
Fails on this line:
```
dst = gdal.open(out, 'w', 'GTiff', tw, th);
```
And returns this error:
```
/Users/adrian/Documents/slippynode/elevator/node_modules/gdal/lib/gdal.js:342
		 	return driver.create.apply(driver, args);
		 	                     ^
Error: Error creating dataset
    at Error (native)
    at Object.open (/Users/adrian/Documents/slippynode/elevator/node_modules/gdal/lib/gdal.js:342:26)
    at reproject (/Users/adrian/Documents/slippynode/elevator/index.js:84:16)
    at /Users/adrian/Documents/slippynode/elevator/index.js:44:9
    at arrayEach (/Users/adrian/Documents/slippynode/elevator/node_modules/lodash/index.js:1317:13)
    at Function.forEach (/Users/adrian/Documents/slippynode/elevator/node_modules/lodash/index.js:5958:11)
    at /Users/adrian/Documents/slippynode/elevator/index.js:42:9
    at listRasters (/Users/adrian/Documents/slippynode/elevator/index.js:149:5)
    at reprojectRaster (/Users/adrian/Documents/slippynode/elevator/index.js:41:5)
    at /Users/adrian/Documents/slippynode/elevator/node_modules/async/lib/async.js:610:21
```
My function is mostly based off of the test in your code for the reprojectImage function.  Also, just trying to create a writable raster in the node terminal interpreter fails with the same error:
```
/Users/adrian/Documents/slippynode/elevator/node_modules/gdal/lib/gdal.js:342
		 	return driver.create.apply(driver, args);
```
Opening an existing file works smoothly.

**Comment by asonnenschein** [comment]
Just a note -- running `gdalwarp` as a subprocess seems to work:
```
  function reproject (input, callback) {

    var src
      , command
      , parsed
      , output
    ;

    parsed = path.parse(input);
    output = path.join(program.outpath, parsed.name + parsed.ext);
    command = 'gdalwarp -t_srs "EPSG:4326" "' + input + '" "' + output + '"';

    exec(command, function (err, stdout, stderr) {
      if (err) callback(err);
      if (stderr) callback(stderr);
      callback();
    });

  };
```

**Comment by brandonreavis** [comment]
Ahh... it seems that the documentation could use some clarification about that. The problem is that when creating a dataset, the `band_count` and `data_type` need to be provided. Try:
```js
var datatype = src.bands.get(1).dataType;
dst = gdal.open(out, 'w', 'GTiff', tw, th, 1,  datatype );
```
Does this work?

**Comment by asonnenschein** [comment]
Nope, my data type is `Float32` if it helps.

**Comment by brandonreavis** [comment]
Also, if you have future problems with the `gdal.open()` method (or any other method) calling `gdal.verbose()` at the beginning of your script to enable all error information to be printed to the console can help. 
```js
> gdal.verbose();
> dst = gdal.open(out, 'w', 'GTiff', tw, th);
ERROR 1: Attempt to create 256x256x0 TIFF file, but width, height and bands
must be positive.
```
Can you try this?

**Comment by asonnenschein** [comment]
Yup, here's my error message from `gdal.verbose()`:
```
ERROR 1: Attempt to create 10x-9 dataset is illegal,sizes must be larger than zero.
```
Weird, because running the process with `gdalwarp` works without error.

**Comment by brandonreavis** [comment]
Ahh yeah there is a problem with your `tw` and `th`. A width of 10 and height of -9 isn't right. I'd recommend using the `gdal.suggestedWarpOutput()` method for determining the right dimensions... This is what gdalwarp does internally. 

Check out this for a basic starting point (ignore the cutline stuff):
https://github.com/naturalatlas/node-gdal/blob/master/test/api_warp.test.js#L236-L249

**Comment by asonnenschein** [comment]
Once again, that solution works.  Thanks!
